import { readFile } from "node:fs/promises";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
const source = (await readFile(process.argv[2]!, "utf8")).replace(/\r/g, "").trimEnd();
const inputs = ["up","down","up","right","up","left","down","left","left","up","right","down","right","right","up","left","down","right","right","down","right","down","down","down","down","right","down","down","down","left","left","up","left","down"];
const pkg = await loadPrototypePackage("prototypes/candle_sokoban"); const adapter = getRuntimeAdapter(pkg.mechanic); const runtime = adapter.createRuntime(pkg.mechanic); const level: LevelDoc = { id: "trace-constrain", title: "trace-constrain", layout: `${source}\n`, global_burn_cycle: 5, win: pkg.mechanic.win }; const initial = adapter.parseLevel(level); let current = initial; const states = [initial]; for (const input of inputs) { const step = runtime.step(current, input as any, { winCondition: pkg.mechanic.win }); if (!step.legal) throw new Error(`trace became illegal at ${input}`); current = step.state; states.push(current); } if (!adapter.isWin(current, pkg.mechanic.win)) throw new Error("trace is not winning");
const keep = new Set<string>(); function add(x: number, y: number): void { keep.add(`${x},${y}`); }
for (const s of states) { add(s.player.x, s.player.y); for (const candle of s.candles) { for (const cell of candle.bodyCells) add(cell.x, cell.y); const cap = candle.bodyCells.at(-1)!; const vector = candle.wickDir === "up" ? [0, -1] : candle.wickDir === "down" ? [0, 1] : candle.wickDir === "left" ? [-1, 0] : [1, 0]; add(cap.x + vector[0]!, cap.y + vector[1]!); } for (const brazier of s.braziers) add(s.braziers[0]!.position.x, s.braziers[0]!.position.y); for (const brazier of s.braziers) add(brazier.position.x, brazier.position.y); }
for (let i = 1; i < states.length; i++) { const before = states[i - 1]!; const after = states[i]!; for (const nextCandle of after.candles) { const prior = before.candles.find((c) => c.id === nextCandle.id); if (!prior) continue; for (let j = 0; j < nextCandle.bodyCells.length; j++) { const a = prior.bodyCells[j] ?? prior.bodyCells[0]!; const b = nextCandle.bodyCells[j] ?? nextCandle.bodyCells[0]!; const dx = Math.sign(b.x - a.x); const dy = Math.sign(b.y - a.y); let x = a.x; let y = a.y; const vector = nextCandle.wickDir === "up" ? [0, -1] : nextCandle.wickDir === "down" ? [0, 1] : nextCandle.wickDir === "left" ? [-1, 0] : [1, 0]; while (true) { add(x, y); if (j === nextCandle.bodyCells.length - 1) add(x + vector[0]!, y + vector[1]!); if (x === b.x && y === b.y) break; x += dx; y += dy; } } } }
const rows = source.split("\n"); for (let y = 0; y < rows.length; y++) for (let x = 0; x < rows[y]!.length; x++) if (rows[y]![x] === "." && !keep.has(`${x},${y}`)) rows[y] = rows[y]!.slice(0, x) + "#" + rows[y]!.slice(x + 1);
console.log(`${rows.join("\n")}\n`);
