import { readFile, writeFile } from "node:fs/promises";
import { enumerateRuntimeGraph } from "../../../../../../src/core/runtimeGraph.js";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { solveWithRuntime } from "../../../../../../src/core/solver.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
import { replayInputSequence } from "../../../../../../src/workflows/inputSequenceReplay.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";
const sourcePath = process.argv[2]!;
const outputPath = process.argv.find((arg) => arg.startsWith("output="))?.slice(7);
function setCell(rows: string[], x: number, y: number, glyph: string): void { const row = rows[y]!; rows[y] = `${row.slice(0, x)}${glyph}${row.slice(x + 1)}`; }
const rows = (await readFile(sourcePath, "utf8")).replace(/\r/g, "").trimEnd().split("\n");
const currentY = rows.findIndex((row, index) => index > 9 && row.includes("o"));
const currentX = currentY >= 0 ? rows[currentY]!.indexOf("o") : -1;
if (currentX >= 0) setCell(rows, currentX, currentY, ".");
setCell(rows, 10, 18, "o");
setCell(rows, 11, 18, "O");
setCell(rows, 12, 16, ".");
for (let y = 14; y <= 17; y += 1) setCell(rows, 9, y, "#");
const layout = `${rows.join("\n")}\n`;
if (outputPath) await writeFile(outputPath, layout, "utf8");
const pkg = await loadPrototypePackage("prototypes/candle_sokoban");
const adapter = getRuntimeAdapter(pkg.mechanic); const runtime = adapter.createRuntime(pkg.mechanic);
const level: LevelDoc = { id: "axis-target18", title: "axis-target18", layout, global_burn_cycle: 5, win: pkg.mechanic.win };
const initial = adapter.parseLevel(level); const options = { winCondition: pkg.mechanic.win };
const solution = solveWithRuntime(runtime, initial, { ...options, maxStates: 300000, maxDepth: 180 });
const replay = replayInputSequence(adapter, runtime, initial, solution.inputs, options, pkg.mechanic.win);
const graph = enumerateRuntimeGraph(runtime, initial, pkg.mechanic.win, options, { maxStates: 300000, terminalizeWins: true });
const forbidden = graph.edges.flatMap((edge) => edge.events.filter((event) => /^(roll_intermediate_|roll_reignite_after_extinguish|wick_reexposed_unlit|shrink_ignite)/.test(event)));
const wins = [...graph.winStateIndexes].map((index) => graph.keys[index]!);
console.log(JSON.stringify({ layout, solution: { found: solution.found, depth: solution.depth, inputs: solution.inputs }, replay: { finalWin: replay.final.isWin, events: replay.steps.flatMap((step) => step.events) }, graph: { status: graph.status, states: graph.keys.length, edges: graph.edges.length, wins: wins.length, signatures: [...new Set(wins.map((key) => key.split("|C:")[1]?.split("|B:")[0] ?? key))] }, forbidden: [...new Set(forbidden)] }, null, 2));
