import { readFile } from "node:fs/promises";
import { enumerateRuntimeGraph } from "../../../../../../src/core/runtimeGraph.js";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { solveWithRuntime } from "../../../../../../src/core/solver.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
import { replayInputSequence } from "../../../../../../src/workflows/inputSequenceReplay.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";

const base=(await readFile(process.argv[2]!,"utf8")).replace(/\r/g,"").trimEnd(); const pkg=await loadPrototypePackage("prototypes/candle_sokoban"); const adapter=getRuntimeAdapter(pkg.mechanic); const runtime=adapter.createRuntime(pkg.mechanic); const options={winCondition:pkg.mechanic.win};
function setCell(layout:string,x:number,y:number,g:string){const rows=layout.split("\n");const row=rows[y]!;rows[y]=`${row.slice(0,x)}${g}${row.slice(x+1)}`;return rows.join("\n");}
function makeLength(n:number){let layout=base;for(let x=7;x<=12;x++)layout=setCell(layout,x,14,".");for(let i=0;i<n-1;i++)layout=setCell(layout,10-n+1+i,14,"1");layout=setCell(layout,10,14,"R");layout=setCell(layout,12,14,"O");return layout;}
const cells=["7,12","8,12","9,12","10,12","11,12","7,13","8,13","9,13","10,13","11,13","7,15","8,15","9,15","10,15","11,15","7,16","8,16","9,16","10,16","11,16","7,17","8,17","9,17","10,17","11,17"];
for(const n of [1,2,3,4,5]){const source=makeLength(n);const patterns:string[][]=[[]];for(const c of cells)patterns.push([c]);for(let i=0;i<cells.length;i++)for(let j=i+1;j<cells.length;j++)patterns.push([cells[i]!,cells[j]!]);for(const walls of patterns){let layout=source;try{for(const c of walls){const [x,y]=c.split(",").map(Number);if(layout.split("\n")[y]![x]!==".")throw new Error();layout=setCell(layout,x,y,"#");}const level:LevelDoc={id:"length-search",title:"length-search",layout:`${layout}\n`,global_burn_cycle:5,win:pkg.mechanic.win};const initial=adapter.parseLevel(level);const sol=solveWithRuntime(runtime,initial,{...options,maxStates:40000,maxDepth:200});if(!sol.found)continue;const rep=replayInputSequence(adapter,runtime,initial,sol.inputs,options,pkg.mechanic.win);const ev=rep.steps.flatMap(s=>s.events);if(!rep.final.isWin||!ev.some(e=>e.startsWith("extinguish_by_wall"))||!ev.some(e=>e.startsWith("ignite_from_brazier")))continue;const graph=enumerateRuntimeGraph(runtime,initial,pkg.mechanic.win,options,{maxStates:40000,terminalizeWins:true});if(graph.status!=="complete")continue;const forbidden=graph.edges.flatMap(e=>e.events.filter(x=>/^(roll_intermediate_|roll_reignite_after_extinguish|wick_reexposed_unlit|shrink_ignite)/.test(x)));if(forbidden.length)continue;const wins=[...graph.winStateIndexes].map(i=>graph.keys[i]!);const sig=[...new Set(wins.map(k=>k.split("|C:")[1]?.split("|B:")[0]??k))];console.log(JSON.stringify({n,walls,depth:sol.inputs.length,states:graph.keys.length,edges:graph.edges.length,wins:wins.length,sig,inputs:sol.inputs,layout:`${layout}\n`},null,2));if(sig.length===1)process.exit(0);}catch{}}}
