import { enumerateRuntimeGraph } from "../../../../../../src/core/runtimeGraph.js";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { solveWithRuntime } from "../../../../../../src/core/solver.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
import { replayInputSequence } from "../../../../../../src/workflows/inputSequenceReplay.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";
const pkg = await loadPrototypePackage("prototypes/candle_sokoban");
const adapter = getRuntimeAdapter(pkg.mechanic); const runtime = adapter.createRuntime(pkg.mechanic); const options = { winCondition: pkg.mechanic.win };
const W=11,H=11;
function empty(){return Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1?"#":".").join("")).join("\n")}
function set(l:string,x:number,y:number,g:string){const r=l.split("\n"),s=r[y]!;r[y]=s.slice(0,x)+g+s.slice(x+1);return r.join("\n")}
function groups(g:ReturnType<typeof enumerateRuntimeGraph>){const p=new Array<number>(g.keys.length).fill(-1),pe=new Array<number>(g.keys.length).fill(-1);for(const[i,e]of g.edges.entries())if(e.to!==0&&pe[e.to]<0){p[e.to]=e.from;pe[e.to]=i}const m=new Map<string,number>();for(const wi of g.winStateIndexes){const ev:string[]=[];for(let c=wi;c!==0&&pe[c]>=0;c=p[c]!)ev.push(...g.edges[pe[c]!]!.events);ev.reverse();const s=ev.filter(e=>/light_brazier|burn_out|win_all_braziers_lit/.test(e)).join("|");m.set(s,(m.get(s)??0)+1)}return[...m.entries()].map(([signature,count])=>({signature,count}))}
const cells:Array<[number,number]>=[];for(let y=2;y<H-2;y++)for(let x=2;x<W-2;x++)cells.push([x,y]);let seed=0x31415926;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/0x1_0000_0000}
for(let it=0;it<10000;it++){let l=empty();const a=[...cells].sort(()=>rnd()-.5),pl=a[0]!,ca=a[1]!,src=a[2]!,tar=a[3]!;l=set(l,pl[0],pl[1],"@");l=set(l,ca[0],ca[1],"U");l=set(l,src[0],src[1],"O");l=set(l,tar[0],tar[1],"o");const wc=10+Math.floor(rnd()*14);for(const[x,y]of a.slice(4,4+wc))l=set(l,x,y,"#");let ini;try{ini=adapter.parseLevel({id:"post-roll",title:"post-roll",layout:l+"\n",global_burn_cycle:5,win:pkg.mechanic.win}as LevelDoc);ini.globalBurnCountdown=4}catch{continue}const sol=solveWithRuntime(runtime,ini,{...options,maxStates:12000,maxDepth:20});if(!sol.found||!sol.inputs)continue;const rep=replayInputSequence(adapter,runtime,ini,sol.inputs,options,pkg.mechanic.win),ev=rep.steps.flatMap(s=>s.events);const last=rep.steps.at(-1)?.events??[];if(!rep.final.isWin||sol.inputs.length!==4||!last.some(e=>e.startsWith("roll_candle"))||!last.some(e=>e.startsWith("burn_out"))||!ev.some(e=>e.startsWith("light_brazier")))continue;const g=enumerateRuntimeGraph(runtime,ini,pkg.mechanic.win,options,{maxStates:12000,terminalizeWins:true});if(g.status!=="complete"||g.winStateIndexes.size===0)continue;const bad=g.edges.flatMap(e=>e.events.filter(x=>/^(roll_intermediate_|roll_reignite_after_extinguish|wick_reexposed_unlit|shrink_ignite|extinguish_by_candle_body)/.test(x)));if(bad.length)continue;const gs=groups(g);if(gs.length===1){console.log(JSON.stringify({it,player:pl,candle:ca,source:src,target:tar,walls:a.slice(4,4+wc),inputs:sol.inputs,events:ev,states:g.keys.length,edges:g.edges.length,wins:g.winStateIndexes.size,groups:gs,layout:l+"\n"},null,2));process.exit(0)}}console.log("NO_UNIQUE")
