import { readFile } from "node:fs/promises";
import { enumerateRuntimeGraph } from "../../../../../../src/core/runtimeGraph.js";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { solveWithRuntime } from "../../../../../../src/core/solver.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
import { replayInputSequence } from "../../../../../../src/workflows/inputSequenceReplay.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";
const source=(await readFile(process.argv[2]!,'utf8')).replace(/\r/g,'').trimEnd();const rows=source.split('\n');const pkg=await loadPrototypePackage('prototypes/candle_sokoban');const a=getRuntimeAdapter(pkg.mechanic);const rt=a.createRuntime(pkg.mechanic);const opt={winCondition:pkg.mechanic.win};function set(l:string,x:number,y:number,g:string){const r=l.split('\n');const s=r[y]!;r[y]=s.slice(0,x)+g+s.slice(x+1);return r.join('\n')}function sig(k:string){return k.split('|C:')[1]?.split('|B:')[0]??k}function test(l:string){let ini;try{ini=a.parseLevel({id:'wall-pair',title:'wall-pair',layout:l+'\n',global_burn_cycle:5,win:pkg.mechanic.win} as LevelDoc)}catch{return null}const sol=solveWithRuntime(rt,ini,{...opt,maxStates:18000,maxDepth:140});if(!sol.found)return null;const rep=replayInputSequence(a,rt,ini,sol.inputs,opt,pkg.mechanic.win);const ev=rep.steps.flatMap(s=>s.events);if(!rep.final.isWin||!ev.some(e=>e.startsWith('extinguish_by_wall'))||!ev.some(e=>e.startsWith('ignite_from_brazier')))return null;const g=enumerateRuntimeGraph(rt,ini,pkg.mechanic.win,opt,{maxStates:18000,terminalizeWins:true});if(g.status!=='complete')return null;const bad=g.edges.flatMap(e=>e.events.filter(x=>/^(roll_intermediate_|roll_reignite_after_extinguish|wick_reexposed_unlit|shrink_ignite)/.test(x)));if(bad.length)return null;const ss=[...new Set([...g.winStateIndexes].map(i=>sig(g.keys[i]!)))];return{depth:sol.inputs.length,states:g.keys.length,edges:g.edges.length,wins:g.winStateIndexes.size,signatures:ss,inputs:sol.inputs,events:ev,layout:l+'\n'}}
const cells:string[]=[];for(let y=1;y<19;y++)for(let x=1;x<13;x++){const g=rows[y]?.[x];if(g!=='.')continue;if((y<=7&&x>=5&&x<=11)||(y>=9&&x>=8&&x<=12))cells.push(`${x},${y}`)}const excluded=new Set(['8,3','8,4','8,5','8,6','8,7','6,4','7,2','8,14','10,14','11,14','8,16']);const candidates=cells.filter(c=>!excluded.has(c));let tried=0;for(let i=0;i<candidates.length;i++)for(let j=i+1;j<candidates.length;j++){const [x1,y1]=candidates[i]!.split(',').map(Number);const [x2,y2]=candidates[j]!.split(',').map(Number);const l=set(set(source,x1,y1,'#'),x2,y2,'#');const r=test(l);tried++;if(r){if(r.signatures.length<=2)console.log(JSON.stringify({walls:[candidates[i],candidates[j]],...r},null,2));if(r.signatures.length===1)process.exit(0)}if(tried%100===0)console.error(`tested ${tried}`)}console.log('NO_UNIQUE');
