import { enumerateRuntimeGraph } from "../../../../../../src/core/runtimeGraph.js";
import { loadPrototypePackage } from "../../../../../../src/core/io.js";
import { solveWithRuntime } from "../../../../../../src/core/solver.js";
import type { LevelDoc } from "../../../../../../src/core/types.js";
import { replayInputSequence } from "../../../../../../src/workflows/inputSequenceReplay.js";
import { getRuntimeAdapter } from "../../../../../../src/prototypes/runtimeAdapter.js";
const pkg=await loadPrototypePackage("prototypes/candle_sokoban"),a=getRuntimeAdapter(pkg.mechanic),rt=a.createRuntime(pkg.mechanic),opt={winCondition:pkg.mechanic.win},W=11,H=11;
function e(){return Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1?"#":".").join("")).join("\n")}
function s(l:string,x:number,y:number,g:string){const r=l.split("\n"),q=r[y]!;r[y]=q.slice(0,x)+g+q.slice(x+1);return r.join("\n")}
function gs(g:ReturnType<typeof enumerateRuntimeGraph>){const p=new Array<number>(g.keys.length).fill(-1),q=new Array<number>(g.keys.length).fill(-1);for(const[i,x]of g.edges.entries())if(x.to!==0&&q[x.to]<0){p[x.to]=x.from;q[x.to]=i}const m=new Map<string,number>();for(const wi of g.winStateIndexes){const v:string[]=[];for(let c=wi;c!==0&&q[c]>=0;c=p[c]!)v.push(...g.edges[q[c]!]!.events);v.reverse();const k=v.filter(x=>/ignite_from_brazier|light_brazier|burn_out|win_all_braziers_lit/.test(x)).join("|");m.set(k,(m.get(k)??0)+1)}return[...m.entries()].map(([signature,count])=>({signature,count}))}
const cells:Array<[number,number]>=[];for(let y=2;y<H-2;y++)for(let x=2;x<W-2;x++)cells.push([x,y]);let z=0x7e57c0de;function rnd(){z=(z*1664525+1013904223)>>>0;return z/0x1_0000_0000}
for(let it=0;it<12000;it++){let l=e();const a1=[...cells].sort(()=>rnd()-.5),pl=a1[0]!,ca=a1[1]!,src=a1[2]!,tar=a1[3]!;l=s(l,pl[0],pl[1],"@");l=s(l,ca[0],ca[1],"u");l=s(l,src[0],src[1],"O");l=s(l,tar[0],tar[1],"o");const wc=10+Math.floor(rnd()*14);for(const[x,y]of a1.slice(4,4+wc))l=s(l,x,y,"#");let ini;try{ini=a.parseLevel({id:"full-unlit-roll",title:"full-unlit-roll",layout:l+"\n",global_burn_cycle:5,win:pkg.mechanic.win}as LevelDoc)}catch{continue}const sol=solveWithRuntime(rt,ini,{...opt,maxStates:14000,maxDepth:30});if(!sol.found||!sol.inputs||sol.inputs.length!==5)continue;const rep=replayInputSequence(a,rt,ini,sol.inputs,opt,pkg.mechanic.win),ev=rep.steps.flatMap(x=>x.events),last=rep.steps.at(-1)?.events??[];if(!rep.final.isWin||!ev.some(x=>x.startsWith("ignite_from_brazier:candle#single"))||!last.some(x=>x.startsWith("roll_candle"))||!last.some(x=>x.startsWith("burn_out")))continue;const g=enumerateRuntimeGraph(rt,ini,pkg.mechanic.win,opt,{maxStates:14000,terminalizeWins:true});if(g.status!=="complete"||g.winStateIndexes.size===0)continue;const bad=g.edges.flatMap(x=>x.events.filter(y=>/^(roll_intermediate_|roll_reignite_after_extinguish|wick_reexposed_unlit|shrink_ignite|extinguish_by_candle_body)/.test(y)));if(bad.length)continue;const groups=gs(g);if(groups.length===1){console.log(JSON.stringify({it,player:pl,candle:ca,source:src,target:tar,walls:a1.slice(4,4+wc),inputs:sol.inputs,events:ev,states:g.keys.length,edges:g.edges.length,wins:g.winStateIndexes.size,groups,layout:l+"\n"},null,2));process.exit(0)}}console.log("NO_UNIQUE")
